name: film_atlasi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.1
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  auto_size_text_field: ^2.2.4
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  youtube_player_flutter: ^9.1.1
  flutter_staggered_animations: ^1.1.1
  palette_generator: ^0.3.3+6
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  lottie: ^2.3.0
  pull_to_refresh_flutter3: ^2.0.2
  grouped_list: ^6.0.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/movie_intro.json
    - assets/animations/loading.json
    - assets/animations/loadingLight.json
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/chat-bg.jpeg
    - assets/animations/loginLoading.json
