// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgTlGwfEj3sp6qU29EmZLe36xB_SpNTM',
    appId: '1:529002028061:web:23e2fd9c65d42a920dfaf4',
    messagingSenderId: '529002028061',
    projectId: 'film-atlasi',
    authDomain: 'film-atlasi.firebaseapp.com',
    databaseURL: 'https://film-atlasi-default-rtdb.firebaseio.com',
    storageBucket: 'film-atlasi.firebasestorage.app',
    measurementId: 'G-2QWJW2D23L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWQUrCTwPjGNnzh39MHGcJvsUDm2t9s8',
    appId: '1:529002028061:android:c60500ec1a9a5f690dfaf4',
    messagingSenderId: '529002028061',
    projectId: 'film-atlasi',
    databaseURL: 'https://film-atlasi-default-rtdb.firebaseio.com',
    storageBucket: 'film-atlasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRMkx0RSEY3-iS5MSnNh3XqBZi3OjoFMo',
    appId: '1:529002028061:ios:8a3f15f1909f7b9c0dfaf4',
    messagingSenderId: '529002028061',
    projectId: 'film-atlasi',
    databaseURL: 'https://film-atlasi-default-rtdb.firebaseio.com',
    storageBucket: 'film-atlasi.firebasestorage.app',
    iosBundleId: 'com.filmatlasi.filmAtlasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRMkx0RSEY3-iS5MSnNh3XqBZi3OjoFMo',
    appId: '1:529002028061:ios:8a3f15f1909f7b9c0dfaf4',
    messagingSenderId: '529002028061',
    projectId: 'film-atlasi',
    databaseURL: 'https://film-atlasi-default-rtdb.firebaseio.com',
    storageBucket: 'film-atlasi.firebasestorage.app',
    iosBundleId: 'com.filmatlasi.filmAtlasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgTlGwfEj3sp6qU29EmZLe36xB_SpNTM',
    appId: '1:529002028061:web:22d71349a79cadac0dfaf4',
    messagingSenderId: '529002028061',
    projectId: 'film-atlasi',
    authDomain: 'film-atlasi.firebaseapp.com',
    databaseURL: 'https://film-atlasi-default-rtdb.firebaseio.com',
    storageBucket: 'film-atlasi.firebasestorage.app',
    measurementId: 'G-NKB0SB07D9',
  );
}
